### ISSUE TITLE
5.0 DataEntryModule

### ISSUE THREAD

**Issue by hafeezminhas** [climsoft/climsoft-app#16]
DataEntryModule Scaffolding
DataEntryModule Routing & Services
DataEntryBaseComponent
DataEntry Tab based navigation
DataEntry DailyForm2 Implementation

**Comment by isedwards** [comment]
**Data entry form behaviour**

1. When the user has not selected station/element/month/year:
An empty data form with _disabled_ fields should be shown (this gives feedback that will be interacting with the correct form before they start choosing station/element etc.)

2. When unsaved data exists in the form, the form navigation ("Daily Config") should be _disabled_ until they explicitly submit, reset or cancel

3. If station/element/month/year are selected then both sections can be _enabled_ whilst changes have not been made to data (the data form may be empty or may contain data loaded from database)

In theory station, element and month/year could be selected in any order:

- if element is chosen first then the user would be limited to stations that record that element

- if date is chosen first then user would be limited to stations that are/were open at that time

**Design**

Could you change the 'Daily Config', 'Units' and 'Daily Data' headings to black on white as shown in the second image below (this is reminiscent of the frame component in Visual Basic and I think it will go down well)?

Also, let's change the "Daily Config" text to "Form Selector".

![image](https://user-images.githubusercontent.com/2097922/160084365-375b1b9f-892a-43cb-922e-fc2a03132cb3.png)
